### ISSUE TITLE
Portrait ratio on screen

### ISSUE THREAD

**Issue by fsto** [fsto/Kinect-Clothes#2]
Mail from Axel:
Eftersom det är stående skärmar, kan ni sätta skärmstorleken till 768x1366
den blir tydligen ihoptryckt annars..

Will solution be to flip the kinect 90 degress? Otherwise it seems to me the captured picture will either have to be cropped or what?

**Comment by niklasnordmark** [comment]
Känns väll som att vrida Kinecten ger bäst resultat. Annars klipps ju
typ halva bilden/djupet. Det kan ju funka att klippa bilden i kanterna
men upplösningen blir rätt låg då. Å andra sidan kanske inte Kinecten
vill läsa poser på höjden?
Va tror ni?

/Niklas

21 mar 2011 kl. 19:26 skrev fsto
reply@reply.github.com:

**Comment by henriq** [comment]
Tror på att klippa bilden, man har väl ingen nytta av att ha massa höjd ändå? Det är nog den lättaste lösningen som blir bra.

**Comment by niklasnordmark** [comment]
Suttit på tåget och räknat lite på det men vill inte push och pulla på edge. Här är iaf vad jag tror kan fixa det:

Ändra första två parametrar i glOrtho (i main.cpp drawfunktionen) till uttrycken nedan. Screen måste sättas innan med nån GL funktion som hämtar screensize (eller fuska och sätt statisk).

Ändringen borde göra att vi bara ritar ut mittersta 270 pixlarna av de 640 som finns på bredden vilket ska ge rätt proportion till skärmstorleken. Man kommer kunna traska ut från bild och kalibrera utanför..

Vänster kant (parameter 1):
(res.X / 2) - (res.Y \* screen.X) / (screen.Y \* 2)
Höger kant (parameter 2):
(res.X / 2) + (res.Y \* screen.X) / (screen.Y \* 2)

res.X = 640
res.Y = 480
screen.X = 768 
screen.Y = 1366

Ger värden ~185 och ~455.

MÖJLIGT PROBLEM: Tveksam om det går att skicka floats till glOrtho. Runda av?

**Comment by fsto** [comment]
Tack grotto för info. Allt funkade. Slängde dessutom in nån GL-grej som hämtar screen resolution dynamiskt.
